#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Stata-DtaReader
version:      0.2
version_from: lib/File/Stata/DtaReader.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
